### ISSUE TITLE
Add more variables? 

### ISSUE THREAD

**Issue by rucko24** [DarkenLight/Bastille-jellyfin#2]
I'm seeing that there are two steps we can save in the Bastillefile using this

```bash
CONFIG set allow.mlock;
CONFIG set allow.raw_sockets;
```

Simply what it does is that it adds them for us in the jails.conf. And if I am not mistaken it would be necessary to add **RESTART** as well.

---

Wouldn't it be possible to add also the URL of the Jellyfin version via variable? with

**ARG**

```bash
ARG JELLYFIN_URL=https://github.com/Thefrank/jellyfin-server-freebsd/releases/download/v10.8.9/jellyfinserver-10.8.9.pkg
ARG JELLYFIN_VERSION=10.8.9
CMD fetch ${JELLYFIN_URL}
PKG jellyfinserver-${JELLYFIN_VERSION}.pkg
CMD ln -s /usr/local/lib/libsqlite3.so /usr/local/lib/libe_sqlite3
SYSRC jellyfinserver_enable=TRUE
SYSRC jellyfinserver_user=jellyfinserver
SYSRC jellyfinserver_group=jellyfinserver
CONFIG set allow.mlock;
CONFIG set allow.raw_sockets;
RESTART
SERVICE jellyfinserver start
# CP config.sh /root
# CMD chmod +x config.sh && ./config.sh
```
```bash
bastille template jellyfin DarkenLight/Bastille-Jellyfin
```

or

```bash
bastille template jellyfin DarkenLight/Bastille-Jellyfin --arg JELLYFIN_URL=https://github.com/Thefrank/jellyfin-server-freebsd/releases/download/v10.8.9/jellyfinserver-10.8.9.pkg --arg JELLYFIN_VERSION=10.8.9
```

**Comment by DarkenLight** [comment]
Thanks a lot for your contribution! to add the jail config in the template, will try the variable part before merging it.

**Comment by DarkenLight** [comment]
> I'm seeing that there are two steps we can save in the Bastillefile using this
> 
> ```shell
> CONFIG set allow.mlock;
> CONFIG set allow.raw_sockets;
> ```
> 
> Simply what it does is that it adds them for us in the jails.conf. And if I am not mistaken it would be necessary to add **RESTART** as well.
> 

Implemented in this commit https://github.com/DarkenLight/Bastille-Jellyfin/commit/e7dea6aadd4f3b49e1699aa8fae77d8198edb5ba

> Wouldn't it be possible to add also the URL of the Jellyfin version via variable? with
> 
> **ARG**
> 
> ```shell
> ARG JELLYFIN_VERSION=10.8.9

Version ARG implemented in this commit https://github.com/DarkenLight/Bastille-Jellyfin/commit/9893e68c0745fe64ac5be6d9894a69365258cbf4

May I kindly ask what are the benefits of having the URL as an ARG in this context? I ask because currently, it seems that only [Thefrank](https://github.com/Thefrank) is making the PKG, but if Jellfin were to officially start building the package for FreeBSD in the future, we could update the URL or provide an ARG to ensure the build process remains flexible. Additionally, please note that I have committed most of the PR, so if there are any issues I may have left unaddressed, please let me know or I will assume that the PR can be closed.

**Comment by rucko24** [comment]
How are you doing? 

It looks great, if you're right, the URL is not needed with the refactor you have done, with the ARG parameter would be enough to pass the current version to install. 

I'm going to try this template in a jail and I'll tell you how it goes. 

Greetings...

---

It has worked correctly.

![image](https://user-images.githubusercontent.com/17187599/223753073-efaa8f03-25da-4b84-83ed-e3bfd01cbcf4.png)


![image](https://user-images.githubusercontent.com/17187599/223753255-8ec1c422-5558-4a6a-94c7-c6520598dcda.png)

**Comment by DarkenLight** [comment]
I am doing great man, what about you? thank you so much for taking the time to test it.

so, everything working as it should, now I am closing this issue, feel free to open a new one if something comes to your mind.
thank you. once again.
